### ISSUE TITLE
Flow about an array of solar photovoltaic panels

### ISSUE THREAD

**Issue by smallduan** [DLR-AE/PanelAero#18]
Hi
I am sorry to bother you. I'm not familiar with aerodynamics, so I'd like to ask you if the method you mentioned can be used to solve the aerodynamics of a flat plate array, such as an array of solar photovoltaic panels (with an elevation angle).

**Comment by ArneVoss** [comment]
I guess the answer is a clear yes and no ;) What aerodynamic quantities are you looking for? 
Calculating the lift of flat panels is exactly what this method is designed for.

**Comment by smallduan** [comment]
Hi 
@ArneVoss  It is my fault , I didn't describe it clearly. I drew a schematic to describe what I mean, just as shown below , I want to know if it can calculate the flat array's total force. 
![image](https://github.com/DLR-AE/PanelAero/assets/52167150/f92c758d-8d66-4f7e-a1b5-94ec262537a0)

**Comment by ArneVoss** [comment]
No Problem. For your case, I propose a more detailed CFD analysis, because I expect large areas of detached flow, e.g. behind the solar panels. Such effects are not captured by aerodynamic panel methods such as the VLM.

**Comment by smallduan** [comment]
Hi 
Thank you very much, I will try it and give feedback here
