### ISSUE TITLE
Facing issues "simplewing_steady.ipynb" while executing the command 

### ISSUE THREAD

**Issue by Preethamkadambi** [DLR-AE/PanelAero#19]
*Note: If this is a general question or difficulty in installing or using the software, please ask in the [Discussions](https://github.com/DLR-AE/PanelAero/discussions) section or contact arne.voss@dlr.de or someone else for help instead.*

# Describe the bug
*Please give a short and clear description of what the bug is and what you expected to happen. Please provide instructions and data to reproduce the problem (model, jcl, etc.). Please provide the smallest working example that reproduces the problem.*

# Bug report checklist
*Please make sure that you have followed the checklist below, many common problems can be solved by:*

- [ ] Consulting the examples.
- [ ] Asking someone for help to make sure there is no obvious mistake in the input.
- [ ] Updating to the newest version of the software (either devel or master branch).

# Your Environment
 - OS: e.g. Linux Redhat 7.9
 - Python version: e.g. 3.8.12
 - Loads Kernel Version: e.g. 2022.08

**Comment by Preethamkadambi** [comment]
While running the example on simplewing_steady.ipynb Jupyternotebook plots = plotting.DetailedPlots(model)
plots.plot_aerogrid(embed_in_notebook=True)

I get the following error message 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 2
      1 plots = plotting.DetailedPlots(model)
----> 2 plots.plot_aerogrid(embed_in_notebook=True)

File [C:\Users/Pritham/DVLM/PanelAero/doc/tutorials\helper_functions\plotting.py:29](file:///C:/Users/Pritham/DVLM/PanelAero/doc/tutorials/helper_functions/plotting.py#line=28), in DetailedPlots.plot_aerogrid(self, scalars, colormap, embed_in_notebook)
     27 if embed_in_notebook:
     28     mlab.init_notebook('png')
---> 29 mlab.figure(bgcolor=(1, 1, 1), size=(600, 450))
     30 src_aerogrid = mlab.pipeline.add_dataset(ug)
     32 # determine if suitable scalar data is given

File [~\.conda\envs\PanelAero\Lib\site-packages\mayavi\tools\figure.py:69](http://localhost:8888/lab/tree/doc/tutorials/simplewing/~/.conda/envs/PanelAero/Lib/site-packages/mayavi/tools/figure.py#line=68), in figure(figure, bgcolor, fgcolor, engine, size)
     67     __scene_number_list.update((name,))
     68     name = 'Mayavi Scene %d' % name
---> 69     engine.new_scene(name=name, size=size)
     70     engine.current_scene.name = name
     71 else:

File [~\.conda\envs\PanelAero\Lib\site-packages\apptools\scripting\recordable.py:48](http://localhost:8888/lab/tree/doc/tutorials/simplewing/~/.conda/envs/PanelAero/Lib/site-packages/apptools/scripting/recordable.py#line=47), in recordable.<locals>._wrapper(*args, **kw)
     45             _outermost_call = True
     46 if not record:
     47     # If the method was not recorded, just call it.
---> 48     result = func(*args, **kw)
     50 return result

File [~\.conda\envs\PanelAero\Lib\site-packages\mayavi\core\engine.py:453](http://localhost:8888/lab/tree/doc/tutorials/simplewing/~/.conda/envs/PanelAero/Lib/site-packages/mayavi/core/engine.py#line=452), in Engine.new_scene(self, viewer, name, **kwargs)
    450             factory_kwargs[arg] = value
    452     viewer = self.scene_factory(**factory_kwargs)
--> 453     process_ui_events()
    455 if name is not None:
    456     viewer.name = name

File [~\.conda\envs\PanelAero\Lib\site-packages\mayavi\core\common.py:81](http://localhost:8888/lab/tree/doc/tutorials/simplewing/~/.conda/envs/PanelAero/Lib/site-packages/mayavi/core/common.py#line=80), in process_ui_events()
     75 """Process GUI events.
     76 
     77 This function merely abstracts the function so nothing is done when
     78 no UI is running.
     79 """
     80 if pyface is not None:
---> 81     pyface.GUI.process_events()

AttributeError: type object 'Unimplemented' has no attribute 'process_events'

**Comment by Preethamkadambi** [comment]
Issue can be fixed by running pip install PyQt5

**Comment by ArneVoss** [comment]
Hello Preetham, 
this sounds like a problem within mayavi... Can you open a normal mayavi figure, e.g. using mlab.figure() ?
If that is not possible, the tutorial can't work.
Two more question:
Have you tried installing the packages for the tutorials with: pip install -e .[tutorials]
And what is your environment?
